apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order-container
        image: kub/order
        ports:
        - containerPort: 8080
      - name: order-logs
        image: busybox
        args: ["sh", "-c", "tail -f /var/order.log"]
        volumeMounts:
        - name: logs
          mountPath: /var
      volumes:
      - name: logs
        emptyDir: {}