apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product-container
        image: product-image:latest
        ports:
        - containerPort: 8080
      - name: product-logs
        image: busybox
        args: ["sh", "-c", "tail -f /var/product.log"]
        volumeMounts:
        - name: logs
          mountPath: /var
      volumes:
      - name: logs
        emptyDir: {}